### PR TITLE
Corrupted wallet

### PR DESCRIPTION
**Pull request by molnard**
If I load this wallet with v1.1.11. my total balance is 0.36148849

After restarting several times it is still this.

The balance should be 0.20310176 BTC

Which is the correct balance?

### CODE REVIEW

**Comment by molnard** [comment]
@yahiheb can you try this if you got the same balance?

https://github.com/molnard/WasabiTestNetWallet/blob/794c54d7fa034f9cce984610f936519ba9c523de/TestNet_1.json

**Comment by yahiheb** [comment]
I deleted the keys and set Height to 0, the first time I tried to load the wallet I got this:

```
2020-04-16 16:10:53 INFO	Wallet (179)	StartAsync finished in 1 minutes.
2020-04-16 16:10:53 INFO	WasabiSynchronizer (257)	Downloaded filter for block 1718955.
2020-04-16 16:10:53 INFO	MempoolService (119)	Start cleaning out mempool...
2020-04-16 16:10:53 INFO	Wallet (273)	ChaumianClient is stopped.
2020-04-16 16:10:54 ERROR	LoadWalletViewModel (226)	System.IO.IOException: The requested operation cannot be performed on a file with a user-mapped section open. : 'C:\Users\RESEAU\AppData\Roaming\WalletWasabi\Client\Wallets\Molnard.json'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at WalletWasabi.Blockchain.Keys.KeyManager.ToFileNoLock(String filePath) in C:\Users\RESEAU\Desktop\WalletWasabi\WalletWasabi\Blockchain\Keys\KeyManager.cs:line 701
   at WalletWasabi.Blockchain.Keys.KeyManager.ToFileNoLock() in C:\Users\RESEAU\Desktop\WalletWasabi\WalletWasabi\Blockchain\Keys\KeyManager.cs:line 687
   at WalletWasabi.Blockchain.Keys.KeyManager.ToFileNoBlockchainStateLock() in C:\Users\RESEAU\Desktop\WalletWasabi\WalletWasabi\Blockchain\Keys\KeyManager.cs:line 675
   at WalletWasabi.Blockchain.Keys.KeyManager.SetBestHeight(Height height) in C:\Users\RESEAU\Desktop\WalletWasabi\WalletWasabi\Blockchain\Keys\KeyManager.cs:line 758
   at WalletWasabi.Wallets.Wallet.ProcessFilterModelAsync(FilterModel filterModel, CancellationToken cancel) in C:\Users\RESEAU\Desktop\WalletWasabi\WalletWasabi\Wallets\Wallet.cs:line 518
   at WalletWasabi.Wallets.Wallet.<>c__DisplayClass93_0.<<LoadWalletStateAsync>b__1>d.MoveNext() in C:\Users\RESEAU\Desktop\WalletWasabi\WalletWasabi\Wallets\Wallet.cs:line 449
--- End of stack trace from previous location where exception was thrown ---
   at WalletWasabi.Stores.IndexStore.ForeachFiltersAsync(Func`2 todo, Height fromHeight, CancellationToken cancel) in C:\Users\RESEAU\Desktop\WalletWasabi\WalletWasabi\Stores\IndexStore.cs:line 441
   at WalletWasabi.Wallets.Wallet.LoadWalletStateAsync(CancellationToken cancel) in C:\Users\RESEAU\Desktop\WalletWasabi\WalletWasabi\Wallets\Wallet.cs:line 445
   at WalletWasabi.Wallets.Wallet.StartAsync(CancellationToken cancel) in C:\Users\RESEAU\Desktop\WalletWasabi\WalletWasabi\Wallets\Wallet.cs:line 187
   at WalletWasabi.Wallets.WalletManager.StartWalletAsync(Wallet wallet) in C:\Users\RESEAU\Desktop\WalletWasabi\WalletWasabi\Wallets\WalletManager.cs:line 200
   at WalletWasabi.Wallets.WalletManager.StartWalletAsync(Wallet wallet) in C:\Users\RESEAU\Desktop\WalletWasabi\WalletWasabi\Wallets\WalletManager.cs:line 209
   at WalletWasabi.Gui.Tabs.WalletManager.LoadWallets.LoadWalletViewModel.<>c__DisplayClass47_0.<<LoadWalletAsync>b__0>d.MoveNext() in C:\Users\RESEAU\Desktop\WalletWasabi\WalletWasabi.Gui\Tabs\WalletManager\LoadWallets\LoadWalletViewModel.cs:line 210
--- End of stack trace from previous location where exception was thrown ---
   at WalletWasabi.Gui.Tabs.WalletManager.LoadWallets.LoadWalletViewModel.LoadWalletAsync() in C:\Users\RESEAU\Desktop\WalletWasabi\WalletWasabi.Gui\Tabs\WalletManager\LoadWallets\LoadWalletViewModel.cs:line 210
2020-04-16 16:10:55 INFO	MempoolService (129)	28 transactions were cleaned from mempool.
```

**Comment by yahiheb** [comment]
So the first time the wallet didn't load.
The second time I got this balance `0.20310176 BTC`.
I was using master.

**Comment by yahiheb** [comment]
Got `0.20310176 BTC` using v1.1.11.

@molnard note that I didn't use the file you mentioned directly but I deleted the keys and set Height to 0.

**Comment by molnard** [comment]
Strange it is working for me. I Copy/Pasted this to a new json file into the Wallets folder and loaded the wallet successfully.
https://raw.githubusercontent.com/molnard/WasabiTestNetWallet/794c54d7fa034f9cce984610f936519ba9c523de/TestNet_1.json

Can you try it again?

**Comment by yahiheb** [comment]
When I use that file as it is the balance I get is 0.
When I delete the keys and set the height to 0 the balance I get is `0.20310176 BTC`.

**Comment by molnard** [comment]
Thx, that is the correct balance. Lucas was able to repro the issue after a few rescan.

**Pull request closed without merging**
